#!/usr/bin/env bash

## chart shaping — the values of every service and module, the vendored charts, direct installs

helm_charts () {

    printf '%s' "${TEMPLATE_DIR}/helm"

}
helm_deploy_dir () {

    printf '%s' "${REPO_ROOT}/${DEPLOY_PATH}"

}
helm_values_dir () {

    printf '%s/helm/values' "${1:-$(helm_deploy_dir)}"

}
helm_values () {

    printf '%s/%s.%s.yaml' "$(helm_values_dir "${2:-}")" "${1:?helm_values needs a name}" "${STACK}"

}
helm_files_dir () {

    printf '%s/argocd/apps/files/%s' "${1:-$(helm_deploy_dir)}" "${STACK}"

}
helm_chart_of () {

    local name="${1:?helm_chart_of needs a name}"

    if [[ " ${SERVICES:-} " == *" ${name} "* ]]; then

        printf 'service'
        return 0

    fi

    [[ " ${MODULES:-} " == *" ${name} "* ]] || die "'${name}' is neither a service nor a module of this project"

    case "$(module_kind "${name}")" in
        tool    ) printf 'tool' ;;
        storage ) die "'${name}' is a binding — it runs no workload of its own" ;;
        *       ) printf 'data' ;;
    esac

}
## vendor the charts argocd reads and the bundle itself into the gitops path — regenerated by every release, never hand-edited
helm_vendor () {

    local deploy="" chart=""

    deploy="$(helm_deploy_dir)"

    ensure_dir "${deploy}/argocd/apps"
    ensure_dir "${deploy}/helm"

    find "${deploy}/argocd/apps" -mindepth 1 -maxdepth 1 ! -name files -exec rm -rf {} +
    cp -R "${TEMPLATE_DIR}/argocd/apps/." "${deploy}/argocd/apps/" || die "Cannot vendor the app-of-apps chart"

    for chart in service data tool gateway observability; do

        rm -rf "${deploy}/helm/${chart}"
        cp -R "$(helm_charts)/${chart}" "${deploy}/helm/${chart}" || die "Cannot vendor the ${chart} chart"

    done

    install -m 0755 "${INFRAX_BIN}" "${deploy}/${INFRAX_NAME}.sh" || die "Cannot vendor the bundle"
    ( cd "${deploy}" && sha256sum "${INFRAX_NAME}.sh" > SHA256SUMS ) || die "Cannot stamp the vendored bundle"

    succ "Charts and the ${INFRAX_NAME} ${INFRAX_VERSION} bundle vendored into ${DEPLOY_PATH} — argocd and CI read this exact tool from the repo."

}
helm_tag () {

    local service="" file="" tag=""

    read -r service _ <<< "${SERVICES:?Missing SERVICES — the release tag rides the services}"

    file="$(helm_values "${service}")"

    [[ ! -f "${file}" ]] || tag="$(sed -n '/^  tag: /{s/^  tag: *"\{0,1\}\([^"]*\)"\{0,1\}$/\1/p;q}' "${file}")"

    [[ -n "${tag}" ]] || die "Stack values carry no image tag: ${file}"

    printf '%s' "${tag}"

}
seed_metrics_namespace () {

    [[ "${OBSERVABILITY_ENABLED}" != "true" ]] || printf '%s' "${OBSERVABILITY_NAMESPACE}"

}
seed_env () {

    local service="${1}" file="" callee="" line="" url="" out=""

    file="$(runtime_dir "$(service_runtime "${service}")")/env"
    url="$(service_url "${service}")"

    while IFS= read -r line; do

        out+=$'\n'"  ${line%%=*}: $(yaml_str "${line#*=}")"

    done < <(

        [[ ! -f "${file}" ]] || ( export SERVICE_NAME="${service}" SERVICE_URL="${url}"; render_text < "${file}"; printf '\n' ) | env_pairs

        for callee in $(service_calls "${service}"); do

            printf '%s=http://%s:%s\n' "$(service_var "${callee}" URL)" "${callee}" "$(service_get "${callee}" PORT)"

        done

    )

    [[ -n "${out}" ]] || out=" {}"

    printf '%s' "${out}"

}
seed_processes () {

    local service="${1}" process="" key="" port="" command="" route="" replicas="" grace="" cpu="" memory="" limit="" out=""

    for process in $(service_processes "${service}"); do

        key="$(model_key "${process}")"
        command="$(service_get "${service}" "${key}_COMMAND")"
        port="$(service_get "${service}" "${key}_PORT")"
        route="$(service_get "${service}" "${key}_ROUTE")"
        replicas="$(service_get "${service}" "${key}_REPLICAS")"
        grace="$(service_get "${service}" "${key}_GRACE")"
        cpu="$(service_get "${service}" "${key}_CPU")"
        memory="$(service_get "${service}" "${key}_MEMORY")"
        limit="$(service_get "${service}" "${key}_MEMORY_LIMIT")"

        [[ "${process}" != "web" || -n "${port}" ]] || port="$(service_get "${service}" PORT)"
        [[ -n "${cpu}" ]] || cpu="$(service_get "${service}" WEB_CPU)"
        [[ -n "${memory}" ]] || memory="$(service_get "${service}" WEB_MEMORY)"
        [[ -n "${limit}" ]] || limit="$(service_get "${service}" WEB_MEMORY_LIMIT)"

        out+=$'\n'"  ${process}:"
        out+=$'\n'"    command: $(argv_json "${command}")"
        out+=$'\n'"    port: ${port:-0}"
        out+=$'\n'"    route: $(yaml_str "${route}")"
        out+=$'\n'"    replicas: ${replicas:-1}"
        out+=$'\n'"    grace: ${grace:-30}"
        out+=$'\n'"    resources:"
        out+=$'\n'"      requests: { cpu: ${cpu}, memory: ${memory} }"
        out+=$'\n'"      limits: { memory: ${limit} }"

    done

    printf '%s' "${out}"

}
seed_provision () {

    local service="${1}" module="" out=""

    for module in $(service_uses "${service}"); do

        [[ "$(module_kind "${module}")" == "database" ]] || continue

        out+="${out:+, }{\"module\": $(yaml_str "${module}"), \"key\": $(yaml_str "$(model_key "${module}")"), \"image\": $(yaml_str "$(module_get "${module}" IMAGE)")"
        out+=", \"user\": $(module_get "${module}" USER), \"host\": $(yaml_str "$(module_host "${module}")"), \"port\": $(module_get "${module}" PORT)"
        out+=", \"extensions\": $(yaml_str "$(module_get "${module}" EXTENSIONS)")}"

    done

    printf '[%s]' "${out}"

}
seed_service () {

    local service="${1}" file="${2}" tag="" storage="" hosts=() callers=()

    [[ ! -f "${file}" ]] || tag="$(sed -n '/^  tag: /{s/^  tag: *"\{0,1\}\([^"]*\)"\{0,1\}$/\1/p;q}' "${file}")"

    mapfile -t hosts < <(service_hosts "${service}")
    mapfile -t callers < <(service_callers "${service}")

    storage="$(service_storage "${service}")"

    SEED_NAME="${service}"
    SEED_RUNTIME="$(service_runtime "${service}")"
    SEED_IMAGE="$(ci_image "${service}")"
    SEED_TAG="${tag:-latest}"
    SEED_PULL_SECRETS="[]"
    SEED_USER="$(service_get "${service}" USER)"
    SEED_PORT="$(service_get "${service}" PORT)"
    SEED_PROBE="$(service_get "${service}" PROBE)"
    SEED_HEALTH="$(service_get "${service}" HEALTH)"
    SEED_ENV="$(seed_env "${service}")"
    SEED_PROCESSES="$(seed_processes "${service}")"
    SEED_REPLICAS_MIN="$(service_get "${service}" REPLICAS_MIN)"
    SEED_REPLICAS_MAX="$(service_get "${service}" REPLICAS_MAX)"
    SEED_CPU_TARGET="$(service_get "${service}" CPU_TARGET)"
    SEED_SURGE="${ROLLOUT_SURGE}"
    SEED_UNAVAILABLE="${ROLLOUT_UNAVAILABLE}"
    SEED_VOLUME=false
    SEED_VOLUME_CLASS="${VOLUME_CLASS}"
    SEED_VOLUME_SIZE="${STORAGE_SIZE}"
    SEED_MOUNT="$(service_get "${service}" MOUNT)"
    SEED_ROUTE=false
    SEED_HOSTS="$(yaml_list "${hosts[@]}")"
    SEED_GATEWAY_NAMESPACE="${GATEWAY_NAMESPACE}"
    SEED_SECTION="${GATEWAY_SECTION}"
    SEED_PROXY_NAMESPACE="${ENVOY_NAMESPACE}"
    SEED_METRICS_NAMESPACE="$(seed_metrics_namespace)"
    SEED_CALLERS="$(yaml_list "${callers[@]}")"
    SEED_MIGRATE="$(argv_json "$(service_get "${service}" MIGRATE)")"
    SEED_PROVISION="$(seed_provision "${service}")"
    SEED_METRICS=""
    SEED_ACCOUNT="$(cloud account_annotations "${service}")"

    [[ "${REGISTRY_PULL}" != "true" ]] || SEED_PULL_SECRETS="[pull-secret]"
    [[ -z "${storage}" ]] || [[ "$(module_mode "${storage}")" != "volume" ]] || SEED_VOLUME=true
    (( ${#hosts[@]} == 0 )) || SEED_ROUTE=true
    [[ -z "${SEED_METRICS_NAMESPACE}" ]] || SEED_METRICS="$(service_get "${service}" METRICS)"

    export SEED_NAME SEED_RUNTIME SEED_IMAGE SEED_TAG SEED_PULL_SECRETS SEED_USER SEED_PORT SEED_PROBE SEED_HEALTH SEED_ENV SEED_PROCESSES \
        SEED_REPLICAS_MIN SEED_REPLICAS_MAX SEED_CPU_TARGET SEED_SURGE SEED_UNAVAILABLE SEED_VOLUME SEED_VOLUME_CLASS SEED_VOLUME_SIZE SEED_MOUNT \
        SEED_ROUTE SEED_HOSTS SEED_GATEWAY_NAMESPACE SEED_SECTION SEED_PROXY_NAMESPACE SEED_METRICS_NAMESPACE SEED_CALLERS SEED_MIGRATE \
        SEED_PROVISION SEED_METRICS SEED_ACCOUNT

    render "$(helm_charts)/values/service.tpl" "${file}"

}
seed_files () {

    local dir="${1}" mode="${2}" file="" body="" out=""

    for file in "${dir}"/*; do

        [[ -f "${file}" ]] || continue

        if [[ "${mode}" == "render" ]]; then body="$(render_text < "${file}" | indent 4)"; else body="$(indent 4 < "${file}")"; fi

        out+=$'\n'"  ${file##*/}: |"$'\n'"${body}"

    done

    [[ -n "${out}" ]] || out=" {}"

    printf '%s' "${out}"

}
seed_uploader () {

    local key="" value=""

    SEED_UPLOADER_IMAGE="${SEED_IMAGE}"
    SEED_UPLOADER_COMMAND='["sh", "-c", "find \"$WORK\" -type f -mtime +\"$KEEP_DAYS\" -delete"]'
    SEED_UPLOADER_ENV="{}"

    [[ "${BACKUP_TARGET}" == "object" ]] || return 0

    while IFS='=' read -r key value; do

        case "${key}" in
            IMAGE   ) SEED_UPLOADER_IMAGE="${value}" ;;
            COMMAND ) SEED_UPLOADER_COMMAND="${value}" ;;
            ENV     ) SEED_UPLOADER_ENV="${value}" ;;
        esac

    done < <(cloud backup_uploader)

}
seed_app () {

    local module="${1}" files="${2}" template="" mode=""

    template="$(module_dir "${module}")/app.yaml"
    mode="$(module_mode "${module}")"

    [[ -f "${template}" && "${OBSERVABILITY_ENABLED}" == "true" ]] || return 0

    SEED_PROJECT="${PROJECT}"
    SEED_NAMESPACE="${K8S_NAMESPACE}"
    SEED_SSLMODE="$(module_get "${module}" "SSLMODE_${mode^^}")"

    export SEED_PROJECT SEED_NAMESPACE SEED_SSLMODE

    render "${template}" "${files}/${module}.yaml"

}
seed_data () {

    local module="${1}" file="${2}" files="${3}" dir="" service="" users=() tools=() databases=()

    dir="$(module_dir "${module}")"

    mapfile -t users < <(module_users "${module}")
    mapfile -t tools < <(model_tools_for "${module}")

    for service in "${users[@]}"; do

        databases+=( "$(model_ident "${service}")" )

    done

    SEED_NAME="${module}"
    SEED_MODE="$(module_mode "${module}")"
    SEED_IMAGE="$(module_get "${module}" IMAGE)"
    SEED_PORT="$(module_get "${module}" PORT)"
    SEED_USER="$(module_get "${module}" USER)"
    SEED_ROOT_USER="$(module_get "${module}" ROOT_USER)"
    SEED_ADDRESS=""
    SEED_CPU="$(module_get "${module}" CPU)"
    SEED_MEMORY="$(module_get "${module}" MEMORY)"
    SEED_MEMORY_LIMIT="$(module_get "${module}" MEMORY_LIMIT)"
    SEED_SIZE="$(module_get "${module}" SIZE)"
    SEED_VOLUME_CLASS="${VOLUME_CLASS}"
    SEED_CLIENTS="$(yaml_list "${users[@]}" "${tools[@]}")"
    SEED_METRICS_NAMESPACE="$(seed_metrics_namespace)"
    SEED_BACKUP=false
    SEED_BACKUP_SCHEDULE="${BACKUP_SCHEDULE}"
    SEED_BACKUP_TARGET="${BACKUP_TARGET}"
    SEED_DATABASES="$(yaml_list "${databases[@]}")"
    SEED_BACKUP_PREFIX="${PROJECT}/${module}"
    SEED_BACKUP_ACCOUNT="$(cloud account_annotations "${module}-backup")"
    SEED_BACKUP_KEEP_DAYS="${BACKUP_KEEP_DAYS}"
    SEED_BACKUP_SIZE="${BACKUP_SIZE}"

    [[ "${SEED_MODE}" != "managed" ]] || SEED_ADDRESS="$(cloud database_address "${module}")"
    [[ ! -f "${dir}/scripts/backup.sh" ]] || (( ${#databases[@]} == 0 )) || SEED_BACKUP=true

    seed_uploader

    export SEED_NAME SEED_MODE SEED_IMAGE SEED_PORT SEED_USER SEED_ROOT_USER SEED_ADDRESS SEED_CPU SEED_MEMORY SEED_MEMORY_LIMIT SEED_SIZE \
        SEED_VOLUME_CLASS SEED_CLIENTS SEED_METRICS_NAMESPACE SEED_BACKUP SEED_BACKUP_SCHEDULE SEED_BACKUP_TARGET SEED_DATABASES \
        SEED_BACKUP_PREFIX SEED_BACKUP_ACCOUNT SEED_BACKUP_KEEP_DAYS SEED_BACKUP_SIZE SEED_UPLOADER_IMAGE SEED_UPLOADER_COMMAND SEED_UPLOADER_ENV

    SEED_SCRIPTS="$(seed_files "${dir}/scripts" raw)"
    SEED_INIT="$(seed_files "${dir}/init" render)"

    export SEED_SCRIPTS SEED_INIT

    render "${dir}/values.tpl" "${file}"

    seed_app "${module}" "${files}"

}
seed_tool () {

    local module="${1}" file="${2}" target="" label="" host="" hosts=() cidrs=() caps=()

    target="$(module_get "${module}" TARGET)"

    for label in $(module_get "${module}" HOST); do

        host="$(model_fqdn "${label}")"
        hosts+=( "${host}" )

    done

    read -ra cidrs <<< "${ADMIN_CIDRS//,/ }"
    read -ra caps <<< "$(module_get "${module}" CAPS)"

    SEED_NAME="${module}"
    SEED_IMAGE="$(module_get "${module}" IMAGE)"
    SEED_PORT="$(module_get "${module}" PORT)"
    SEED_USER="$(module_get "${module}" USER)"
    SEED_CAPS="$(yaml_list "${caps[@]}")"
    SEED_HEALTH="$(module_get "${module}" HEALTH)"
    SEED_TARGET="${target}"
    SEED_TARGET_PORT="$(module_get "${target}" PORT)"
    SEED_TARGET_USER="$(module_get "${target}" ROOT_USER)"
    SEED_PROJECT="${PROJECT}"
    SEED_EMAIL="${SSL_EMAIL:-admin@${BASE_DOMAIN:-${LINT_DOMAIN}}}"
    SEED_URL=""
    SEED_ROUTE=false
    SEED_HOSTS="$(yaml_list "${hosts[@]}")"
    SEED_AUTH='""'
    SEED_CIDRS="$(yaml_list "${cidrs[@]}")"
    SEED_GATEWAY_NAMESPACE="${GATEWAY_NAMESPACE}"
    SEED_SECTION="${GATEWAY_SECTION}"
    SEED_PROXY_NAMESPACE="${ENVOY_NAMESPACE}"
    SEED_CPU="$(module_get "${module}" CPU)"
    SEED_MEMORY="$(module_get "${module}" MEMORY)"
    SEED_MEMORY_LIMIT="$(module_get "${module}" MEMORY_LIMIT)"

    if (( ${#hosts[@]} )); then

        SEED_ROUTE=true
        SEED_AUTH="$(k8s_tools_auth)"
        SEED_URL="https://${hosts[0]}/"

    fi

    export SEED_NAME SEED_IMAGE SEED_PORT SEED_USER SEED_CAPS SEED_HEALTH SEED_TARGET SEED_TARGET_PORT SEED_TARGET_USER SEED_PROJECT SEED_EMAIL \
        SEED_URL SEED_ROUTE SEED_HOSTS SEED_AUTH SEED_CIDRS SEED_GATEWAY_NAMESPACE SEED_SECTION SEED_PROXY_NAMESPACE SEED_CPU SEED_MEMORY SEED_MEMORY_LIMIT

    render "$(module_dir "${module}")/values.tpl" "${file}"

}
seed_cloud () {

    local files="${1}" template=""

    template="$(cloud metrics_file)"

    [[ -n "${template}" && "${CLOUD_METRICS}" == "true" && "${OBSERVABILITY_ENABLED}" == "true" ]] || return 0

    render "${template}" "${files}/cloud-metrics.yaml"

}
## derive every service, module and app file of this stack from the manifest — overwrites hand edits, commit the result
helm_seed () {

    local root="${1:-$(helm_deploy_dir)}" dir="" files="" service="" module=""

    model_verify

    dir="$(helm_values_dir "${root}")"
    files="$(helm_files_dir "${root}")"

    ensure_dir "${dir}"
    rm -rf "${files}"
    ensure_dir "${files}"

    for service in ${SERVICES}; do seed_service "${service}" "${dir}/${service}.${STACK}.yaml"; done
    for module in $(model_modules "database cache"); do seed_data "${module}" "${dir}/${module}.${STACK}.yaml" "${files}"; done
    for module in $(model_modules tool); do seed_tool "${module}" "${dir}/${module}.${STACK}.yaml"; done

    seed_cloud "${files}"

    succ "Seeded '${STACK}' — ${SERVICES}${MODULES:+ · ${MODULES}}; topology only, the release decides the image tag."

}
## write the image tag into every service this stack carries
helm_bump () {

    local tag="${1:?Missing image tag}" service=""

    for service in ${SERVICES}; do

        sed -i "s|^  tag: .*|  tag: \"${tag}\"|" "$(helm_values "${service}")" || die "Cannot bump the tag of ${service}"

    done

    succ "Image tag → ${tag}"

}
## lint every chart against every values file this stack carries
helm_lint () {

    local root="${1:-}" name="" chart=""

    ensure helm

    for name in ${SERVICES:-} $(model_modules "database cache tool"); do

        chart="$(helm_chart_of "${name}")"
        run helm lint --quiet "$(helm_charts)/${chart}" -f "$(helm_values "${name}" "${root}")"

    done

    run helm lint --quiet "$(helm_charts)/gateway" --set-json "hostnames=[\"${LINT_DOMAIN}\"]" --set sslEmail="${LINT_EMAIL}"
    run helm lint --quiet "$(helm_charts)/observability" --set host="${LINT_DOMAIN}"
    run helm lint --quiet "${TEMPLATE_DIR}/argocd/apps" --set stack="${STACK}"

    succ "Helm charts lint clean."

}
## render the chart of one service or module to stdout
helm_template () {

    local name="${1:?Usage: helm template <service|module> [values-root]}" root="${2:-}" chart=""

    ensure helm

    chart="$(helm_chart_of "${name}")"

    helm template "${name}" "$(helm_charts)/${chart}" -f "$(helm_values "${name}" "${root}")" -n "${K8S_NAMESPACE}"

}
## install one service or module directly, bypassing argocd (confirmed)
helm_deploy () {

    local name="${1:?Usage: helm deploy <service|module>}" chart=""

    ensure helm

    chart="$(helm_chart_of "${name}")"

    confirm "Deploy '${name}' directly with helm (bypassing ArgoCD)?"

    run helm upgrade --install "${name}" "$(helm_charts)/${chart}" \
        -f "$(helm_values "${name}")" \
        -n "${K8S_NAMESPACE}" --create-namespace \
        --wait --timeout "${HELM_TIMEOUT}"

}
## diff one rendered chart against the cluster
helm_diff () {

    ensure helm kubectl

    helm_template "$@" | kubectl diff -f - || true

}
## remove one direct helm release (confirmed)
helm_uninstall () {

    local name="${1:?Usage: helm uninstall <service|module>}"

    ensure helm

    confirm "Uninstall release '${name}' from '${K8S_NAMESPACE}'?"

    run helm uninstall "${name}" -n "${K8S_NAMESPACE}"

}
